import { StyleSheet } from "react-native";
import colors from "./colors";

const itemWidth = (330 - 23 - 10) / 4;

export default StyleSheet.create({
  board: {
    flex: 1,
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.background,
  },
  timerContainer: {
    width: 100,
    height: 100,
    borderRadius: 15,
    position: "relative",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.letterColor,
    borderWidth: 5,
    borderColor: colors.letterColor,
    shadowColor: colors.letterColor,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.5,
    shadowRadius: 6,
  },
  addedTime: {
    top: -12,
    position: "absolute",
    color: colors.timerColor,
    fontSize: 35,
    fontWeight: "800",
  },
  timer: {
    color: colors.timerColor,
    fontSize: 55,
    fontWeight: "800",
  },
  currentStringContainer: {
    width: 200,
    height: 100,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  currentString: {
    zIndex: 2,
    fontSize: 25,
    fontWeight: "800",
    padding: 4,
    borderRadius: 10,
    borderWidth: 2,
  },
  prevString: {
    position: "absolute",
    zIndex: 1,
    fontSize: 25,
    fontWeight: "800",
    padding: 4,
    borderRadius: 10,
    borderWidth: 2,
  },
  gridBoard: {
    width: 344,
    height: 344,
    padding: 5,
    backgroundColor: colors.boardBackground,
    borderWidth: 5,
    borderColor: colors.border,
    borderRadius: 15,
    shadowColor: colors.letterColor,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.5,
    shadowRadius: 10,
  },
  gridItems: {
    flexDirection: "row",
    flexWrap: "wrap",
    width: "100%",
    height: "100%",
    padding: 5,
    gap: 5,
  },
  gridItem: {
    alignItems: "center",
    justifyContent: "center",
    width: itemWidth,
    height: itemWidth,
    backgroundColor: colors.letterBackground,
    borderWidth: 3,
    borderColor: colors.letterColor,
    borderRadius: 10,
    shadowColor: colors.letterColor,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.5,
    shadowRadius: 3,
  },
  activeGridItemIncorrect: {
    backgroundColor: colors.invalid,
    borderColor: colors.invalidBorder,
  },
  activeGridItemCorrect: {
    backgroundColor: colors.valid,
    borderColor: colors.border,
  },
  alreadyFound: {
    backgroundColor: colors.alreadyFound,
    borderColor: colors.alreadyFoundBorder,
  },
  oneUse: {
    color: "orange",
  },
  twoUse: {
    color: "red",
  },
  letter: {
    fontWeight: "800",
    fontSize: 55,
    color: colors.letterColor,
  },
});
