import { StyleSheet } from "react-native";
import colors from "./colors";

const itemWidth = (330 - 23 - 10) / 4;

export default StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.background,
    alignItems: "center",
    justifyContent: "center", 
  },
  board: {
    flex: 1,
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  timerTopRight: {
    position: "absolute",
    top: 16,
    right: 16,
    zIndex: 10,
  },
  timer: {
    color: colors.timerColor,
    fontSize: 55,
    fontWeight: "800",
  },
  characterWindow: {
    width: "25%",
    aspectRatio: 0.7,
    backgroundColor: "#0b1522",
    borderTopLeftRadius: 100,
    borderTopRightRadius: 100,
    borderWidth: 1,
    borderColor: "#ffffff15",
    alignItems: "center",
    justifyContent: "center",
  },
  characterWindowText: {
    color: "#ffffff30",
    fontSize: 14,
  },
  addedTime: {
    top: -12,
    position: "absolute",
    color: colors.timerColor,
    fontSize: 35,
    fontWeight: "800",
  },
  currentStringContainer: {
    width: 200,
    height: 100,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  currentString: {
    zIndex: 2,
    fontSize: 25,
    fontWeight: "800",
    padding: 4,
    borderRadius: 10,
    borderWidth: 2,
  },
  prevString: {
    position: "absolute",
    zIndex: 1,
    fontSize: 25,
    fontWeight: "800",
    padding: 4,
    borderRadius: 10,
    borderWidth: 2,
  },
  gridBoard: {
    width: 344,
    height: 344,
    padding: 5,
    backgroundColor: colors.boardBackground,
    borderWidth: 5,
    borderColor: colors.border,
    borderRadius: 15,
    shadowColor: colors.letterColor,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.5,
    shadowRadius: 10,
  },
  gridItems: {
    flexDirection: "row",
    flexWrap: "wrap",
    width: "100%",
    height: "100%",
    padding: 5,
    gap: 5,
  },
  gridItem: {
    alignItems: "center",
    justifyContent: "center",
    width: itemWidth,
    height: itemWidth,
    backgroundColor: colors.letterBackground,
    borderWidth: 3,
    borderColor: colors.letterColor,
    borderRadius: 10,
    shadowColor: colors.letterColor,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.5,
    shadowRadius: 3,
  },
  activeGridItemIncorrect: {
    backgroundColor: colors.invalid,
    borderColor: colors.invalidBorder,
  },
  activeGridItemCorrect: {
    backgroundColor: colors.valid,
    borderColor: colors.border,
  },
  alreadyFound: {
    backgroundColor: colors.alreadyFound,
    borderColor: colors.alreadyFoundBorder,
  },
  oneUse: {
    color: "orange",
  },
  twoUse: {
    color: "red",
  },
  letter: {
    fontWeight: "800",
    fontSize: 55,
    color: colors.letterColor,
  },
  resetButton: {
    width: "60%",
    height: 50,
    borderRadius: 12,
    backgroundColor: "#1a1a2e",
    overflow: "hidden",
    position: "relative",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    marginTop: 20,
    borderWidth: 1,
    borderColor: "#ffffff20",
  },
  resetButtonFill: {
    position: "absolute",
    left: 0,
    top: 0,
    height: "100%",
    backgroundColor: "#95d5b2",
    opacity: 0.4,
  },
  resetButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "600",
    zIndex: 1,
  },
  resetButtonLocked: {
    borderColor: "#ffffff10",
    opacity: 0.5,
  },
  resetButtonFillLocked: {
    backgroundColor: "#ffffff",
    opacity: 0.15,
  },
  resetButtonTextLocked: {
    color: "#ffffff60",
  },
});
